POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "email": "ccccaitiezhu@qq.com",
  "username": "caitiezhu",
  "nameZh": "菜铁柱",
  "aboutMe": "懒狗",
  "password": "caiyang123"
}

###

